In [4]:
#q1 a
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reversed_array = arr[::-1]
print(reversed_array)

[6 5 4 3 2 1]


In [6]:
#b 
array = np.array([[1, 2, 3], [2, 4, 5], [3, 6,7]])
flatten_array = array.flatten()
print(flatten_array)

[1 2 3 2 4 5 3 6 7]


In [7]:
#c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
compared_array = np.array_equal(arr1, arr2)
print(compared_array)

True


In [11]:
#d
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(x)
print(np.bincount(x).argmax())
print(y)
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
1
[1 1 1 2 3 4 2 4 3 3]
1


In [17]:
#e
array_gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
totalsum = np.sum(array_gfg)
print(totalsum)
totalsum1 = np.sum(array_gfg, axis=1)
print(totalsum1)
totalsum2 = np.sum(array_gfg, axis=0)
print(totalsum2)

45
[[20  9 16]]
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [19]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag = np.trace(n_array)
eigenvalues,eigenvectors = np.linalg.eig(n_array)
inverse_matrix =  np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print(diag)
print(eigenvalues)
print(eigenvectors)
print(inverse_matrix)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [25]:
#g
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1,q1)
conv1 = np.cov(p1,q1)
print(product1)
print(conv1)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
covariance2 = np.cov(p2.T, q2.T)

print(product2)
print(covariance2)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [26]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])


inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian_product = np.array(np.meshgrid(x, y)).T.reshape(-1, 2)

print(inner_product)
print(outer_product)
print(cartesian_product)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [27]:
#Q2
#(a)
array = np.array([[1, -2, 3],[-4, 5, -6]])

abs_values = np.abs(array)
flattened_array = array.flatten()
percentiles_flat = np.percentile(flattened_array, [25, 50, 75])
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)
mean_flat = np.mean(flattened_array)
median_flat = np.median(flattened_array)
std_flat = np.std(flattened_array)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print(abs_values)
print(percentiles_flat)
print(percentiles_col)
print(percentiles_row)
print(mean_flat, median_flat, std_flat)
print(mean_col, median_col, std_col)
print(mean_row, median_row, std_row)


[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
[ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]


In [28]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print(floor_values)
print(ceiling_values)
print(truncated_values)
print(rounded_values)



[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [31]:
#Q3 (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print(sorted_array)
sortest_indices = np.argsort(array)
smallest_elements = np.partition(array, 4)[:4]
largest_elements = np.partition(array, -5)[-5:]
print(sorted_array)
print(sortest_indices)
print(smallest_elements)
print(largest_elements)


[ 10  16  16  52  54  62 453]
[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[16 10 16 52]
[ 16  52  62  54 453]


In [32]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]
print(integer_elements)
print(float_elements)


[1. 2. 3. 2.]
[1.2 2.2]


In [18]:
from PIL import Image
import numpy as np
path ="dog.jpg"
def img_to_array(path):
    try:
        # Open the image
        image = Image.open(path)
        
        # Convert the image to a numpy array
        img_array = np.array(image)
        
        # Determine the filename based on the image mode (RGB or greyscale)
        if img_array.ndim == 3:  # RGB Image
            filename = "image_rgb.txt"
        else:  # Greyscale Image
            filename = "image_greyscale.txt"
        
        # Save the array to a text file
        np.savetxt(filename, img_array.reshape(-1, img_array.shape[-1] if img_array.ndim == 3 else 1), fmt='%d' if img_array.ndim == 3 else '%.2f', delimiter=',')
        
        print(f"Image saved as {filename}")
    except Exception as e:
        print(f"Error: {e}")

# Example usage with a relative path
path = "dog.jpg"  # Update this path to point to your image file
img_to_array(path)


Image saved as image_rgb.txt
